### ISSUE TITLE
Changing details screen style

### ISSUE THREAD

**Issue by victoreronmosele** [JideGuru/FlutterSuperHeroes#6]
Rearrange items in the details screen to make information easier to pick apart

**Comment by victoreronmosele** [comment]
I am working on this and should make a PR soon.

**Comment by JideGuru** [comment]
Thanks, i will be waiting for the PR.

**Comment by JideGuru** [comment]
I guess this is done. https://github.com/JideGuru/FlutterSuperHeroes/pull/8
